package constants

// Error messages
const (
	// ErrorFileNotFound is the error message when a file is not found
	ErrorFileNotFound = "File not found"
	// ErrorFileRead is the error message when a file cannot be read
	ERRORCODE_BOOKMARK_EXISTS = "ERROR_BOOKMARK_EXISTS"
	ERRORMSG_BOOKMARK_EXISTS  = "Bookmark already exists"

	ERRORCODE_UNKNOWN_ERROR = "ERROR_UNKNOWN"
	ERRORMSG_UNKNOWN_ERROR  = "Unknown error"

	ERRORMSG_BOOKMARK_NOT_FOUND  = "Bookmark not found"
	ERRORCODE_BOOKMARK_NOT_FOUND = "ERROR_BOOKMARK_NOT_FOUND"

	ERRORMSG_INVALID_URL  = "Invalid URL"
	ERRORCODE_INVALID_URL = "ERROR_INVALID_URL"

	ERRORMSG_INVALID_File  = "Invalid File"
	ERRORCODE_INVALID_File = "ERROR_INVALID_FILE"

	ERRORMSG_UNAUTHENTICATED  = "Unauthenticated"
	ERRORCODE_UNAUTHENTICATED = "UNAUTHENTICATED"

	ERRORMSG_BOOKMARK_PENDING  = "Indexing in progress"
	ERRORCODE_BOOKMARK_PENDING = "INDEXING_IN_PROGRESS"

	ERRORMSG_INVALID_EMAIL  = "Invalid email"
	ERRORCODE_INVALID_EMAIL = "ERROR_INVALID_EMAIL"

	ERRORMSG_MAGICLINK_FAILED  = "Could not send magic link"
	ERRORCODE_MAGICLINK_FAILED = "ERROR_MAGICLINK_FAILED"

	ERRORMSG_INVALID_DETAIL  = "Invalid details"
	ERRORCODE_INVALID_DETAIL = "ERROR_INVALID_DETAIL"

	ERRORMSG_INTERNAL_ERROR   = "Invalid server error"
	ERRORCODE_INTERNAL_DETAIL = "ERROR_INTERNAL_ERROR"

	ERRORMSG_INVALID_ORG_ID  = "Invalid org id"
	ERRORCODE_INVALID_ORG_ID = "ERROR_INVALID_ORG_ID"

	ERRORMSG_USER_NOT_FOUND  = "User not found"
	ERRORCODE_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"

	ERRORMSG_INVALID_PASSWORD  = "Invalid password"
	ERRORCODE_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD"
)
